site_name: My Reference
pages:
    - Home: index.md
    - CheatSheets:
      - VS Code: vscode_cheatsheet.md
      - Linux: linux_cheatsheet.md
      - Jupyter: jupyter_cheatsheet.md
    - Python:
      - Installation: python-installation.md
      - Editor: python-editor.md
    - Mysql: mysql.md
    - Sqlalchemy: sqlalchemy.md
    - Markdown: markdown.md
    - Docker: docker.md
    - Hive: hive.md

theme: readthedocs