site_name: My Reference
pages:
    - Home: index.md
    - CheatSheets:
      - VS Code: vscode_cheatsheet.md
      - Linux: linux_cheatsheet.md
      - Jupyter: jupyter_cheatsheet.md
      - Git: git_cheatsheet.md
      - Python: python_cheatsheet.md
    - Python:
      - Installation: python-installation.md
      - Virtual environment: python-virtual-environment.md
      - Editor: python-editor.md
    
    - Database:
      - Mysql: mysql.md
      - Sqlalchemy: sqlalchemy.md
      - Postgresql: postgresql.md
      - Elasticsearch: elasticsearch.md

    - Data Engineering:
      - Hive: hive.md
    
    
    - Data analysis & processing:
      - Apache Tika: apache_tika.md
      - Pandas: pandas.md
      - Anaconda: anaconda.md 
      - Facebook duckling: facebook_duckling.md
    - Linux:
      - Sox: sox.md
      - Screen: linux_screen.md
      - Tree: linux_tree.md
      - Zip: linux_zip.md

    - Markdown: markdown.md
    - Docker: docker.md
    - Nginx: nginx.md
    - Wordpress: wordpress.md

theme: readthedocs